runtime: nodejs12
handlers:
- url: /([\w-\/]+)$
  static_files: dist/index.html
  upload: dist/index.html
  mime_type: text/html; charset=UTF-8
  expiration: 1m

- url: /(.*\.(js))
  static_files: dist/\1
  upload: dist/(.*\.(js))
  mime_type: application/javascript; charset=UTF-8

- url: /(.*\..*)
  static_files: dist/\1
  upload: dist/(.*)
